### ISSUE TITLE
Enable IPv4 and IPv6 address auto-assignment

### ISSUE THREAD

**Issue by ethanjli** [sargassum-world/fluitans#163]
We need to expose an HTML form-based interface to allow automatic assignment of IPv4 addresses to devices from some subnet. This is needed for Google Chrome to be able to access web servers in the ZeroTier network, because it does not resolve AAAA DNS records on IPv4-only networks. We'd also need a way to add and update A records for members with assigned domain names, after the ZeroTier network controller assigns an IPv4 address to the device; ideally this would be automatic, for a more seamless UI.

We need this for two reasons:
- The current version of Planktoscope software might be listening on `0.0.0.0` rather than `::` (and the configuration for the MQTT broker is unclear). A proper fix would be to address that problem, but as a workaround for now we should assign IPv4 addresses on the ZeroTier networks with Planktoscopes as members.
- On IPv4-only networks, Google Chrome refuses to resolve AAAA-only domain names. See https://bugs.chromium.org/p/chromium/issues/detail?id=530482 and https://chromium.googlesource.com/chromium/src/+/HEAD/net/dns/README.md for more details. The latter link proposes a workaround of adding a network route to `2001:4860:4860::8888` with a UDP socket listener; but every ZeroTier device would have to enable public routes when it joins the network in order to take advantage of this workaround, which is too much to ask of device.

Sub-tasks:
- [x] Enable checkbox toggles for the various IPv6 and IPv4 auto-assignment modes (#164)
- [x] Show the RFC4193 addresses in the devices list when they're assigned (#164)
- [x] Automatically update the list of IP addresses assigned to each network member when the IPv6 NDP modes are changed (#164)
- [x] Display managed routes as forms, including a way to add a managed route (#165)
- [x] Display form for setting IP assignment pools when auto-assignment modes are enabled (include both checkboxes for the full range of a managed route and text input) (#165)
- [x] Enable specifying an IPv4 CIDR to auto-assign (#165)
- [x] Enable manually assigning an IP address (#165)
- [x] Automatically include NDP and assigned IP addresses in AAAA and A RRsets upon domain name assignment  (#167)
- [x] Add a button to force an update of AAAA and A records with IP addresses (#167)
- [x] Display differences between AAAA and A records and the actual IP assignments, and only show the force-update button when there are differences; when differences appear or disappear, the device card should auto-refresh on the network page (#167)
- [x] Automatically update AAAA and A RRsets which have discrepancies from assigned IP addresses, as a background worker (this will require moving `getMemberRecords` and `DNSUpdate` code from the routes section to a client, e.g. the main client package, so that we can make a background worker) (#167)
